# Generated by Django 5.1.1 on 2024-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_hints_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='nc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
