# Generated by Django 5.1.1 on 2024-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenges_nc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesresults',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengesresults',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
