# Generated by Django 5.1.1 on 2024-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challengesresults_points_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesresults',
            name='solved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
