# Generated by Django 5.1.1 on 2024-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challengesresults_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesresults',
            name='points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
